class Letter {
  final String word;
  final String voice;
  Letter({required this.word, required this.voice});
}

final List<Letter> letters = [
  Letter(word: 'آ', voice: 'voices/Voice 001.m4a'),
  Letter(word: 'ا', voice: 'voices/Voices 001.m4a'),
  Letter(word: 'ب', voice: 'voices/Voice 002.m4a'),
  Letter(word: 'پ', voice: 'voices/Voice 003.m4a'),
  Letter(word: 'ت', voice: 'voices/Voice 004.m4a'),
  Letter(word: 'ث', voice: 'voices/Voice 005.m4a'),
  Letter(word: 'ج', voice: 'voices/Voice 006.m4a'),
  Letter(word: 'چ', voice: 'voices/Voice 007.m4a'),
  Letter(word: 'ح', voice: 'voices/Voice 008.m4a'),
  Letter(word: 'خ', voice: 'voices/Voice 009.m4a'),
  Letter(word: 'د', voice: 'voices/Voice 010.m4a'),
  Letter(word: 'ذ', voice: 'voices/Voice 011.m4a'),
  Letter(word: 'ر', voice: 'voices/Voice 012.m4a'),
  Letter(word: 'ز', voice: 'voices/Voice 013.m4a'),
  Letter(word: 'س', voice: 'voices/Voice 015.m4a'),
  Letter(word: 'ش', voice: 'voices/Voice 016.m4a'),
  Letter(word: 'ص', voice: 'voices/Voice 017.m4a'),
  Letter(word: 'ض', voice: 'voices/Voice 018.m4a'),
  Letter(word: 'ط', voice: 'voices/Voice 019.m4a'),
  Letter(word: 'ظ', voice: 'voices/Voice 020.m4a'),
  Letter(word: 'ع', voice: 'voices/Voice 021.m4a'),
  Letter(word: 'غ', voice: 'voices/Voice 022.m4a'),
  Letter(word: 'ف', voice: 'voices/Voice 023.m4a'),
  Letter(word: 'ق', voice: 'voices/Voice 024.m4a'),
  Letter(word: 'ک', voice: 'voices/Voice 025.m4a'),
  Letter(word: 'گ', voice: 'voices/Voice 026.m4a'),
  Letter(word: 'ل', voice: 'voices/Voice 027.m4a'),
  Letter(word: 'م', voice: 'voices/Voice 028.m4a'),
  Letter(word: 'ن', voice: 'voices/Voice 029.m4a'),
  Letter(word: 'و', voice: 'voices/Voice 030.m4a'),
  Letter(word: 'ه', voice: 'voices/Voice 031.m4a'),
  Letter(word: 'ی', voice: 'voices/Voice 032.m4a'),
];

final List<String> single_letters = [
  'آب',
  'آرد',
  'ابر',
  'اسم',
  'ام',
  'باد',
  'بار',
  'بال',
  'بام',
  'بحر',
  'برف',
  'برق',
  'برگ',
  'بز',
  '(موتر)بس',
  'بوت',
  'بیل',
  'پا',
  'پر',
  'پول',
  'پیر',
  'تار',
  'تیل',
  'چاق',
  'چه',
  'چاه',
  'حرف',
  'حق',
  'حوت',
  'حوض',
  'خاک',
  'خام',
  'خر',
  'خوب',
  'خون',
  'داس',
  'داش',
  'داغ',
  'دزد',
  'دشت',
  'دست',
  'دهل',
  'دوست',
  'دود',
  'دروغ',
  'دین',
  'روز',
  'زرد',
  'زن',
  'سال',
  'سبز',
  'سخت',
  'سرد',
  'سنگ',
  'سگ',
  'سیب',
  'شاخ',
  'شرم',
  'شام',
  'صلح',
  'صبح',
  'صفر',
  'ضرب',
  'ظهر',
  'عطر',
  'عید',
  'فرد',
  'فیل',
  'قلب',
  'قتل',
  'قهر',
  'کارت',
  'کم',
  'کوه',
  'گاز',
  'گاو',
  'گرم',
  'گرگ',
  'لب',
  'ما',
  'مار',
  'ماش',
  'ماه',
  'ماین',
  'مرد',
  'مرغ',
  'من',
  'مو',
  'وقت',
  'ویل(چرخ)',
];

final List<String> double_letters = [
  'آبشار',
  'آبی',
  'آدرس',
  'اتاق',
  'احمق',
  'ارزان',
  'اره',
  'استاد',
  'بادام',
  'بادغیس',
  'بالشت',
  'بخار',
  'بسکیت',
  'پادشاه',
  'پاسپورت',
  'پاک',
  'پایتخت',
  'تابلو',
  'تاریخ',
  'تاریک',
  'جوزا',
  'جیگر',
  'جلد',
  'جمله',
  'چارمغز',
  'چاقو',
  'چاکلیت',
  'حساب',
  'حلوا',
  'حلال',
  'خراب',
  'خرگوش',
  'خرما',
  'دانش',
  'داکتر',
  'درست',
  'راستی',
  'راضی',
  'روشن',
  'زانو',
  'زبان',
  'زیاد',
  'ساختن',
  'ساعت',
  'ساکت',
  'شجاع',
  'شاگرد',
  'شادی',
  'صابون',
  'صفحه',
  'طاووس',
  'طبله',
  'طرف',
  'ظروف',
  'عادت',
  'عاید',
  'عدد',
  'فامیل',
  'فایده',
  'فردا',
  'قیمت',
  'کابل',
  'کاسه',
  'کارگر',
  'گادی',
  'گرام',
  'گرده',
  'لاجورد',
  'لاشتک',
  'لباس',
  'محفل',
  'مردم',
  'مرطوب',
  'ناخن',
  'نارنج',
  'نازک',
  'واضح',
  'واکسین',
  'والی',
  'وزیر',
];

final List<String> triple_letters = [
  'آب میوه',
  'آببازی',
  'استخوان',
  'اسلحه',
  'باادب',
  'بادپکه',
  'بادرنگ',
  'پرسیدن',
  'پس فردا',
  'پلاستیک',
  'تابستان',
  'تجارت',
  'تباشیر',
  'ثانیه',
  'جایزه',
  'جای نماز',
  'جلغوزه',
  'چپرکت',
  'چهارشنبه',
  'حل کردن',
  'حیوانات',
  'خداوند',
  'خارجی',
  'خربوزه',
  'درس دادن',
  'در میان',
  'ذخیره',
  'ذوب شدن',
  'رخصتی',
  'رستورانت',
  'ستاره',
  'سرطان',
  'شفتالو',
  'شکستن',
  'صحتمند',
  'صمیمی',
  'ضعف کردن',
  'طبقه',
  'طیاره',
  'علاقه',
  'علامه',
  'غیر حاضر',
  'غرق شدن',
  'فاتحه',
  'فابریکه',
  'فاصله',
  'قبرستان',
  'قالب گوش',
  'کار کردن',
  'کامیاب',
  'کچالو',
  'گذاشتن',
  'گذشته',
  'مایعات',
  'مثلث',
  'محصل',
  'نوشیدن',
  'ناراحت',
  'نوشیدن',
  'وارخطا',
  'واسلین',
  'والیبال',
];

final List<String> multiple_letters = [
  'آب و هوا',
  'آشپزخانه',
  'آغازکردن',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];
