import 'package:flutter/material.dart';
import '../components/hover_letters.dart';

class OneSyllable extends StatelessWidget {
  OneSyllable({super.key});

  final List<String> letters = [
    'آب',
    'آرد',
    'ابر',
    'اسم',
    'ام',
    'باد',
    'بار',
    'بال',
    'بام',
    'بحر',
    'برف',
    'برق',
    'برگ',
    'بز',
    '(موتر)بس',
    'بوت',
    'بیل',
    'پا',
    'پر',
    'پول',
    'پیر',
    'تار',
    'تیل',
    'چاق',
    'چه',
    'چاه',
    'حرف',
    'حق',
    'حوت',
    'حوض',
    'خاک',
    'خام',
    'خر',
    'خوب',
    'خون',
    'داس',
    'داش',
    'داغ',
    'دزد',
    'دشت',
    'دست',
    'دهل',
    'دوست',
    'دود',
    'دروغ',
    'دین',
    'روز',
    'زرد',
    'زن',
    'سال',
    'سبز',
    'سخت',
    'سرد',
    'سنگ',
    'سگ',
    'سیب',
    'شاخ',
    'شرم',
    'شام',
    'صلح',
    'صبح',
    'صفر',
    'ضرب',
    'ظهر',
    'عطر',
    'عید',
    'فرد',
    'فیل',
    'قلب',
    'قتل',
    'قهر',
    'کارت',
    'کم',
    'کوه',
    'گاز',
    'گاو',
    'گرم',
    'گرگ',
    'لب',
    'ما',
    'مار',
    'ماش',
    'ماه',
    'ماین',
    'مرد',
    'مرغ',
    'من',
    'مو',
    'وقت',
    'ویل(چرخ)',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('One Syllable'),
      ),
      backgroundColor: Color.fromRGBO(25, 35, 54, 1),
      body: SingleChildScrollView(
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                GridView.count(
                  shrinkWrap: true,
                  crossAxisCount: 5,
                  crossAxisSpacing: 8,
                  mainAxisSpacing: 12,
                  children: letters
                      .map((letter) => HoverLetter(letter: letter))
                      .toList(),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
